apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume              # PV name

spec:
  capacity:
    storage: 1Gi               # Total storage size

  accessModes:
    - ReadWriteOnce            # Only one Pod can use it at a time

  hostPath:
    path: /data                # Path on Node machine (local storage)
